languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "Gemfile.lock"
- "coverage/assets/0.10.0/application.js"
- "features/step_definitions/web_steps.rb"
- "app/assets/**/*"
- "app/assets/**/**/*"
- "public/assets/**/*"
- "public/assets/**/**/*"
